# version: "3.8"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       args:
#         NGINX_VERSION: ${NGINX_VERSION}
#         PHP_VERSION: ${PHP_VERSION}
#     container_name: moodle-app
#     restart: always
#     ports:
#       - "80:80"
#       - "443:443"
#     env_file: .env
#     volumes:
#       - ./moodle:/var/www/html
#       - ./moodledata:/var/moodledata
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./php-fpm.conf:/usr/local/php/etc/php-fpm.conf
#       - ./www.conf:/usr/local/php/etc/php-fpm.d/www.conf
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     container_name: moodle-db
#     restart: always
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:


version: '3.9'

services:
  moodle-app:
    build:
      context: .
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    env_file: .env
    container_name: app-moodle
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/moodledata
    ports:
      - "8080:80"
    depends_on:
      - moodle-db

  moodle-db:
    image: postgres:13
    container_name: db-moodle
    environment:
      POSTGRES_DB: ${MOODLE_DB_NAME}
      POSTGRES_USER: ${MOODLE_DB_USER}
      POSTGRES_PASSWORD: ${MOODLE_DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MOODLE_DB_USER} -d ${MOODLE_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
